name: lab10
description: "A Flutter project using OpenStreetMap"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^8.2.2
  location: ^5.0.0
  http: ^1.6.0
  latlong2: ^0.9.0
  area:
    path: packages/area

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  # If you need map styling later, you can place it here
  # assets:
  #   - assets/map_style.json
